name: CI workflow

on: [push]

jobs:
  info:
    runs-on: ubuntu-latest
    name: Information Gathering

    steps:
      - name: print PWD
        run: pwd
        
      - name: kernel info
        run: uname -a

      - name: ip address
        run: ip addr
        
      - name: available commands
        run: ls /usr/bin
        
  permissions:
    runs-on: ubuntu-latest
    name: A job to find user permissions

    steps:
      - name: get user id
        run: id
      - name: home info
        run: ls -ald $HOME
      

